######################################################################
# Automatically generated by qmake (3.0) Wed Nov 19 16:13:17 2014
######################################################################

TEMPLATE = app
TARGET = primes
INCLUDEPATH += .
QT += widgets
LIBS += -pthread

# Input
HEADERS += primes.h stringListModel.h QStreamThreaded.h
SOURCES += main.cpp primes.cpp stringListModel.cpp QStreamThreaded.cpp

CONFIG += debug
