######################################################################
# Automatically generated by qmake (3.0) Wed Nov 19 16:13:17 2014
######################################################################

TEMPLATE = app
TARGET = primes
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += primes.h stringListModel.h
SOURCES += main.cpp primes.cpp stringListModel.cpp
